services:
  - type: web
    name: hubedu
    env: node
    repo: https://github.com/lfonzie/HE-next
    branch: main
    rootDir: .
    buildCommand: npm install --prefer-offline --no-audit && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENEM_API_BASE
        value: https://enem-api.onrender.com/v1
      - key: ENEM_FALLBACK_MODEL
        value: gpt-4o-mini
      - key: NEXTAUTH_URL
        value: https://your-hubedu-app.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false # Prompt for value during deployment
      - key: DATABASE_URL
        sync: false # Prompt for value during deployment
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: enem-api
    env: node
    repo: https://github.com/lfonzie/HE-next
    branch: main
    rootDir: enem-api-main
    buildCommand: npm install --prefer-offline --no-audit && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 11000
      - key: DATABASE_URL
        sync: false # Prompt for value during deployment
    healthCheckPath: /api/health
    autoDeploy: true