services:
  - type: web
    name: hubedu-nextjs
    env: node
    plan: starter
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main