name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install HubEdu dependencies
        run: npm install
        
      - name: Build HubEdu
        run: npm run build
        
      - name: Install ENEM API dependencies
        working-directory: ./enem-api-main
        run: npm install
        
      - name: Generate Prisma client
        working-directory: ./enem-api-main
        run: npx prisma generate
        
      - name: Build ENEM API
        working-directory: ./enem-api-main
        run: npm run build
        
      - name: Run HubEdu linting
        run: npm run lint
        
      - name: Run ENEM API linting
        working-directory: ./enem-api-main
        run: npm run lint
